# Generated by Django 3.0.4 on 2020-03-31 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadavre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Introduce un título', max_length=200, verbose_name='Título')),
                ('code', models.CharField(help_text='Introduce un código secreto', max_length=200, verbose_name='Código')),
            ],
        ),
        migrations.CreateModel(
            name='CadavrePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Introduce la continuación', verbose_name='Continuación')),
                ('author', models.CharField(help_text='Introduce tu nombre', max_length=200, verbose_name='Autor')),
                ('cadavre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Cadavre')),
            ],
            options={
                'ordering': ['cadavre', 'id'],
            },
        ),
    ]
