# Generated by Django 3.0.4 on 2020-04-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadavre',
            name='code',
            field=models.CharField(help_text='Introduce un código secreto', max_length=200, unique=True, verbose_name='Código'),
        ),
    ]
